services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.0
    container_name: zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kafka:
    image: confluentinc/cp-kafka:7.5.0
    container_name: kafka
    ports:
      - "9092:9092"
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  mysql:
    image: mysql:8.0
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: datapipeline
      MYSQL_USER: sparkuser
      MYSQL_PASSWORD: sparkpass
    ports:
      - "3307:3306"  # Changed host port to avoid conflict
    volumes:
      - mysql_data:/var/lib/mysql

  pyspark:
    build: ./pyspark
    container_name: pyspark
    ports:
      - "4040:4040"
      - "8888:8888"
    volumes:
      - ./notebooks:/home/notebooks
    depends_on:
      - kafka
      - mysql
    environment:
      - SPARK_MASTER=spark://pyspark:7077
      - PYSPARK_PYTHON=python3.11

  airflow:
    build: ./airflow
    container_name: airflow
    ports:
      - "8080:8080"
    environment:
      - AIRFLOW__CORE__LOAD_EXAMPLES=False
    volumes:
      - ./dags:/opt/airflow/dags
      - ./logs:/opt/airflow/logs
    command: ["bash", "-c", "airflow db init && airflow webserver"]
    depends_on:
      - kafka
      - zookeeper
      - mysql

  kafka-client:
    build:
      context: ./kafka
    container_name: kafka-client
    depends_on:
      - kafka
    volumes:
      - ./kafka:/app

volumes:
  mysql_data:
